# Generated by Django 5.2 on 2025-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_status_sensores_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='unidade_med',
            field=models.CharField(choices=[('°C', '°C'), ('lux', 'lux'), ('%', '%'), ('num', 'num')], default='°C', max_length=3),
        ),
    ]
