# Generated by Django 5.2 on 2025-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ambientes_descricao_alter_sensores_unidade_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('temperatura', 'temperatura'), ('luminosidade', 'luminosidade'), ('umidade', 'umidade'), ('contador', 'contador')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='status',
            field=models.CharField(choices=[('ativo', 'ativo'), ('inativo', 'inativo')], max_length=8),
        ),
    ]
