# Generated by Django 5.2 on 2025-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sensores_sensor_alter_sensores_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
